addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 6}], "Previous lectures: how to train a model *given data* (tokenizer, architecture, optimizer, GPU/kernels, parallelism, scaling laws)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 8}], "Next 4 lectures: *what data* to train on?", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 10}], "Hot take: the most important thing in training foundation models is data.", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 12}], "One justification is seeing what companies disclose.", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 13}], "Open models (e.g., Llama 2) have full transparency into architecture, but no information on data", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 14}], "Llama 2: 'from publicly available sources' (section 2.1)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 14}], "https://arxiv.org/pdf/2307.09288", {"color": "gray"})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 15}], "Reasons for secrecy: (i) competitive dynamics and (ii) copyright liability", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 17}], "Before foundation models, data work meant heavy annotation.", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 18}], "Now there's less annotation, data work but there's still a lot of curation and cleaning.", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 19}], "Data is fundamentally a long-tail problem, scales with human effort (unlike architectures, systems).", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 21}], "Example: Dolma 1.7 dataset from AI2", {})
addImage([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 22}], "https://miro.medium.com/v2/resize:fit:828/format:webp/1*QFZ9R3xZUH8stKchJz9G7w.png", {"width": "100.0%"})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 23}], "What are these sources? How are they chosen and processed?", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 25}], "Types of data objects", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 26}], "- Live service (e.g., Reddit)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 27}], "- Raw snapshot (via crawling or API or dumps)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 28}], "- Processed text (via various filtering and transformations)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 29}], "- Aggregated datasets (e.g., Dolma, The Pile)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 31}], "Goal: large, high quality, diverse data", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 64}], "## Lecture 11", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 65}], "Raw sources (e.g., Common Crawl, GitHub)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 66}], "Processing (e.g., HTML -> text)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 68}], "## Lecture 12", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 69}], "Quality (e.g., keeping Wikipedia-like documents)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 70}], "Toxicity (e.g., removing harmful content)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 72}], "## Lecture 13", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 73}], "Privacy (e.g., removing PII)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 74}], "Copyright (e.g., avoid books?)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 75}], "Deduplication (e.g., using minhash)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 76}], "Train-test overlap (removing test sets from training)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 78}], "## Lecture 14", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 79}], "Reweighting (e.g., DoReMi)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 80}], "Continued pre-training (e.g., improving long-context, reasoning)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 82}], "Focus: data for pretraining", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 33}, {"name": "overview", "filename": "lecture_11.py", "lineno": 83}], "Out of scope: alignment data, benchmark data", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 35}], "Plan: historical tour of datasets used for model training, use as a springboard to dive more deeply into the raw sources", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 87}], "BERT [Devlin+ 2019]", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 87}], "https://arxiv.org/pdf/1810.04805", {"color": "gray"})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 89}], "Data consists of:", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}], "- BooksCorpus (800M words)", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}, {"name": "books_corpus", "filename": "lecture_11.py", "lineno": 98}], "Smashwords: founded in 2008, allow anyone to self-publish an e-book", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}, {"name": "books_corpus", "filename": "lecture_11.py", "lineno": 99}], "2024: 150K authors, 500K books", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}, {"name": "books_corpus", "filename": "lecture_11.py", "lineno": 101}], "BooksCorpus [2015]", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}, {"name": "books_corpus", "filename": "lecture_11.py", "lineno": 101}], "https://en.wikipedia.org/wiki/BookCorpus", {"color": "gray"})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}, {"name": "books_corpus", "filename": "lecture_11.py", "lineno": 102}], "Self-published books priced at $0, scraped from Smashwords", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}, {"name": "books_corpus", "filename": "lecture_11.py", "lineno": 103}], "7K books, 985M words", {})
addText([{"name": "lecture_11", "filename": "lecture_11.py", "lineno": 38}, {"name": "bert", "filename": "lecture_11.py", "lineno": 90}, {"name": "books_corpus", "filename": "lecture_11.py", "lineno": 104}], "Has been taken down because violated Smashwords terms-of-service", {})
